spring:
  thymeleaf:
    prefix: classpath:/templates/
    mode: HTML
    cache: false
    encoding: UTF-8
    #     新版本不支持content-type: text/html，故新写法
    servlet:
      content-type: text/html

  mail:
    host: smtp.163.com
    default-encoding: UTF-8
    protocol: smtp
    username: changyao2@163.com
    password: TAUQTZSOXEVXJYFV
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  data:
    mongodb:
      uri: mongodb://root:password@localhost:27017/admin
server:
  port: 8081
